### ISSUE TITLE
Crash while shopping

### ISSUE THREAD

**Issue by Shumpd2** [TheIrateSeagoer/pd2lootfilter#1]
Getting a crash to desktop using your defualt filter, I was shopping for Tp staffs in act 2 hell when I hover a staff I would get instant CTDT no msg or prompt, I have no idea what the mod is on the staff that causes this.
thanks for the hard work just thought i would let you know.

**Comment by TheIrateSeagoer** [comment]
Thanks for letting me know. I too encountered this issue, and removed the tiered colorization of individual staffmods. I've spent the last 20 minutes shopping act 2 hell and have not crashed yet. So it should be smooth sailing for you moving forward.
